canal.ip =
canal.port = 11111
canal.destinations = search_cdc_raw
canal.auto.scan = false
canal.instance.global.mode = spring
canal.instance.global.lazy = false
canal.instance.global.spring.xml = classpath:spring/file-instance.xml
canal.instance.tsdb.enable = false

canal.serverMode = rabbitmq
canal.mq.flatMessage = true
canal.mq.canalBatchSize = 50
canal.mq.canalGetTimeout = 100
canal.mq.topic = search.cdc.raw

rabbitmq.host = rabbitmq
rabbitmq.port = 5672
rabbitmq.username = guest
rabbitmq.password = guest
rabbitmq.virtual.host = /
rabbitmq.exchange = search.cdc.raw.exchange
rabbitmq.deliveryMode = 2
