input {
  file {
    path => "PATH_TO_NEXUS_LOG"
    start_position => "beginning"
    sincedb_path => "SINCE_DB_PATH"
    codec => plain { charset => "UTF-8" }
  }
}

filter {
  grok {
    match => {
      "message" => "%{TIMESTAMP_ISO8601:log_ts} %{LOGLEVEL:level} \[%{DATA:thread}\] %{DATA:logger} - %{GREEDYDATA:json_payload}"
    }
  }

  json {
    source => "json_payload"
    skip_on_invalid_json => true
  }

  if [event] != "reaction_like" {
    drop { }
  }

  mutate {
    remove_field => ["message", "json_payload", "log_ts", "level", "thread", "logger"]
  }
}

output {
  kafka {
    bootstrap_servers => "KAFKA_BOOTSTRAP_SERVERS"
    topic_id => "topic_like_monitor"
    codec => json
  }
}
