CREATE TABLE IF NOT EXISTS post_counter_projection (
    post_id BIGINT NOT NULL PRIMARY KEY,
    author_id BIGINT NOT NULL,
    projected_published TINYINT NOT NULL DEFAULT 0,
    last_event_id BIGINT NOT NULL DEFAULT 0,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
