# 开发环境占位配置
logging:
  level:
    cn.nexus: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nexus_social?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  sql:
    init:
      mode: never

mybatis:
  mapper-locations: classpath*:mapper/social/*.xml
  configuration:
    map-underscore-to-camel-case: true

feed:
  inbox:
    maxSize: 1000
    ttlDays: 30
  outbox:
    maxSize: 1000
    ttlDays: 30
  fanout:
    batchSize: 200
  rebuild:
    perFollowingLimit: 20
    inboxSize: 200
    maxFollowings: 2000
    lockSeconds: 30
  follow:
    compensate:
      recentPosts: 20
  bigv:
    followerThreshold: 500000
    coreFanMaxPush: 2000
    pull:
      maxBigvFollowings: 200
      perBigvLimit: 50
    pool:
      enabled: false
      buckets: 4
      maxSizePerBucket: 500000
      ttlDays: 7
      fetchFactor: 30
      triggerFollowings: 200

interaction:
  like:
    windowSeconds: 60
    delayBufferSeconds: 10
    syncTtlSeconds: 180
    flushLockSeconds: 30
